---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-DOM
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 0
  XML::Parser: 2.30
  XML::Parser::PerlSAX: 0.07
  XML::RegExp: 0
version: 1.46
